### ISSUE TITLE
Does expert/contact also get an ICS file?

### ISSUE THREAD

**Issue by katrinleinweber** [slub/slub_events#22]
https://github.com/slub/slub_events/blob/7a28df4568cdc43102cd2dd67557a1aeec87a3fe/Documentation/Introduction/Index.rst#L25-L26

I tried to find out from [EmailHelper.php](https://github.com/slub/slub_events/blob/fcbca93256f2a184b1f5bdb1fb34111030c7da25/Classes/Helper/EmailHelper.php) whether the expert _also_ receives that/an invitation. Searching for "contact" as well there, it didn't became clear to me, tough. [Contact.php](https://github.com/slub/slub_events/blob/7a28df4568cdc43102cd2dd67557a1aeec87a3fe/Classes/Domain/Model/Contact.php) OTOH doesn't mention "ics", but neither does [Subscriber.php](https://github.com/slub/slub_events/blob/7a28df4568cdc43102cd2dd67557a1aeec87a3fe/Classes/Domain/Model/Subscriber.php).

Is maybe `sender` the expert, or the system? Thanks for any info on this :-)

**Comment by albig** [comment]
Yes, of course it receives an ICS file. Have a look at the createAction in the [SubscriberController](https://github.com/slub/slub_events/blob/master/Classes/Controller/SubscriberController.php#L208).

**Comment by katrinleinweber** [comment]
Ah! Awesome :-)
