### ISSUE TITLE
Error in Backend module after filter for only recurring

### ISSUE THREAD

**Issue by percolatorWitt** [slub/slub_events#27]
I got an Exception/CMS/1264678095 after check the checkbox "checkbox-only-recurring".

The big problem was, that the filter is saved. Every time I select the backend module,  I got this error.

$query->in expects an array. I had a string.

**Comment by albig** [comment]
Thank you for your bugreport. Which TYPO3 version are you using? Did you use current slub_events release?

**Comment by percolatorWitt** [comment]
I use TYPO3 7.6.32. The version of the extension is 2.4.1. I will upgarde sooon ;-)

**Comment by albig** [comment]
I can reproduce this issue with TYPO3 8.7 with PHP 7.2. 

Which PHP version do you use? Just noticed, TYPO3 7.6 mentions no maximum PHP version anymore. I had in mind, it's only compatible up to 7.0.

**Comment by percolatorWitt** [comment]
I have this error on TYPO3 7.6 with PHP 5.6 and PHP 7.1.
