### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by SiMackL** [slub/slub_events#33]
Für User ungewohnte Datumsanzeige in den Meldungen bei der Speicherung einer Veranstaltung, (statt 27.03.2019 03/27/19)  in HookPreProcessing.php Zeile 262:
$formatedTimeString = gmstrftime('%a, %x %H:%M:%S', $dt->format('U')); 
possible:
$formatedTimeString = gmstrftime('%d.%m.%Y %H:%M', $dt->format('U'));
Thanks
Silvia

**Comment by albig** [comment]
That's not an issue of slub_events but the locale setting seems to be wrong.

The '%x' format means "Preferred date representation based on locale, without the time." 

So please checkt the backend language and if PHP locales for de_DE are available on the server.
