### ISSUE TITLE
Wrong namespace for pagination template in TypoScript

### ISSUE THREAD

**Issue by PeaceSfiSh** [slub/slub_events#48]
The fully-qualified name for **PaginateViewHelper** is still **TYPO3\CMS\Fluid\ViewHelpers\Widget\PaginateViewHelper**, in TYPO3 v9 & v10. But it was faulty replaced in setup.txt by moving to TYPO3Fluid namespace in commit bb0e54e46481680d5e1b47efcbe6736d77b03db0

Please revert
`TYPO3Fluid\Fluid\ViewHelpers\Widget\PaginateViewHelper`
to
`TYPO3\CMS\Fluid\ViewHelpers\Widget\PaginateViewHelper`
in
`Configuration/TypoScript/setup.txt`

**Comment by albig** [comment]
Thank you for your report.
