### ISSUE TITLE
Make backend module header compatible with TYPO3 v10

### ISSUE THREAD

**Issue by twaurisch** [slub/slub_events#62]
In the current state the backend module isn't completely compatible with TYPO3 v10.
This can be seen in the screenshot in PR #60 

<img width="1513" alt="Backend Module TYPO3 v10" src="https://user-images.githubusercontent.com/3354500/111310479-6a64bf00-865d-11eb-9cb9-5949838fb984.png">

To solve this I want to discuss about moving all backend actions to a separate controller class, because it seems to be necessary to use **BackendTemplateView::class or ModuleTemplate::class**. Using these in the existing controllers could result in duplicated code or a more complex inheritance, for controllers providing a backend action. That's because of the initialization of the view.

**Comment by PeaceSfiSh** [comment]
This one should be solved with PR #65

**Comment by chrode** [comment]
Checked and working.
